# Generated by Django 3.1.3 on 2021-01-15 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=50)),
                ('followers', models.ManyToManyField(blank=True, default=None, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
