# Generated by Django 3.1.3 on 2021-01-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='followers',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='follower',
            name='star',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
