# Generated by Django 3.1.3 on 2021-01-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='owner',
        ),
    ]
